# Change baseurl before deploy
baseurl = "https://maosong.website"
languageCode = "en-us"
title = "Mao Song(毛松)'s Homepage"
description = "Mao Song's technical blog covering machine learning, large language models (LLMs), deep learning research, and AI innovations. ."

# Enable emoji support
enableEmoji = true

# Enable Git info for lastmod dates
enableGitInfo = true

# Theme i18n support
# Available values: en, fr, id, ja, ko, pt-br, zh-cn, zh-tw, es, de, nl, it, th, el, uk, ar
defaultContentLanguage = "en"

# Set hasCJKLanguage to true if DefaultContentLanguage is in [zh-cn ja ko]
# This will make .Summary and .WordCount behave correctly for CJK languages.
hasCJKLanguage = true

[author]
name = "Mao Song"

[pagination]
pagerSize = 5


[sitemap]
  changefreq = "weekly"
  priority = 0.8
  filename = "sitemap.xml"

# Privacy settings
[privacy]
  [privacy.googleAnalytics]
    anonymizeIP = true
    respectDoNotTrack = true
  [privacy.youtube]
    privacyEnhanced = true

[build]
writeStats = true

[minify]
disableXML = false
minifyOutput = true

[outputs]
home = ["HTML", "RSS", "JSON"]

[taxonomies]
  category = "categories"
  tag = "tags"