# Pages placed under these sections will be shown on homepage and archive page.
mainSections = ["post"]
# Output page's full content in RSS.
rssFullContent = true
favicon = "/favicon.png"

[footer]
since = 2020
customText = ""

[dateFormat]
published = "January 2, 2006"
lastUpdated = "January 2, 2006 at 3:04 PM"

[sidebar]
emoji = "üç•"
subtitle = "Never stop learning."

[sidebar.avatar]
enabled = true
local = true
src = "img/avatar.jpg"

[article]
headingAnchor = true
math = true
readingTime = true
showTags = true 

[article.license]
enabled = true
default = "Licensed under CC BY-NC-SA 4.0"

## Widgets
[[widgets.homepage]]
type = "search"

[[widgets.homepage]]
type = "archives"
[widgets.homepage.params]
limit = 5

[[widgets.homepage]]
type = "categories"
[widgets.homepage.params]
limit = 20

[[widgets.homepage]]
type = "tag-cloud"
[widgets.homepage.params]
limit = 20

[[widgets.page]]
type = "toc"

[opengraph.twitter]
site = ""
card = "summary_large_image"

[defaultImage.opengraph]
enabled = true
local = true
src = "img/avatar.jpg"

[colorScheme]
toggle = true
default = "auto"

[imageProcessing.cover]
enabled = true
resizeOptions = ["800x600 webp q80"]

[imageProcessing.content]
enabled = true
resizeOptions = ["800x600 webp q80"]

## Comments
[comments]
enabled = true
provider = "utterances"

[comments.disqusjs]
shortname = ""
apiUrl = ""
apiKey = ""
admin = ""
adminLabel = ""

[comments.utterances]
repo = "MaoSong2022/MaoSong2022.github.io"
issueTerm = "pathname"
label = ""

[comments.remark42]
host = ""
site = ""
locale = ""

[comments.vssue]
platform = ""
owner = ""
repo = ""
clientId = ""
clientSecret = ""
autoCreateIssue = false

[comments.waline]
serverURL = ""
lang = ""
visitor = ""
avatar = ""
emoji = ["https://cdn.jsdelivr.net/gh/walinejs/emojis/weibo"]
requiredMeta = ["name", "email", "url"]
placeholder = ""

[comments.waline.locale]
admin = "Admin"

[comments.twikoo]
envId = ""
region = ""
path = ""
lang = ""

[comments.cactus]
defaultHomeserverUrl = "https://matrix.cactus.chat:8448"
serverName = "cactus.chat"
siteName = ""

[comments.giscus]
repo = ""
repoID = ""
category = ""
categoryID = ""
mapping = ""
lightTheme = ""
darkTheme = ""
reactionsEnabled = 1
emitMetadata = 0

[comments.gitalk]
owner = "MaoSong2022"
admin = "MaoSong2022"
repo = "blog-comments"
clientID = "Ov23liR14pGD8RphGsPI"

[comments.cusdis]
host = ""
id = ""

[analytics]
simpleAnalytics = true

[[widgets.homepage]]
type = "featured"
[widgets.homepage.params]
    title = "Featured Research"
    limit = 3