# Author information
[author]
  name = "Mao Song"

mainSections = ["post"]
rssFullContent = true
favicon = "/favicon.png"
smoothScroll = true
google_verify = "b98b42ee66064915aab3225026b2e9ca"

[footer]
  since = 2020
  customText = ""

[dateFormat]
  published = "January 2, 2006"
  lastUpdated = "January 2, 2006 at 3:04 PM"

[sidebar]
  subtitle = "Never stop learning."

[sidebar.avatar]
  enabled = true
  local = true
  src = "img/avatar.jpg"

[article]
  headingAnchor = true
  math = true
  readingTime = true
  showTags = true 

[article.license]
  enabled = true
  default = "Licensed under CC BY-NC-SA 4.0"

[article.footer]
  enabled = true

[analytics]
  simpleAnalytics = true
